name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  docs:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.zensical.outputs.page_url }}
    steps:
      - name: Zensical Action
        id: zensical
        uses: cssnr/zensical-action@v1
